server:
  port: 7070
spring:
  application:
    name: gateway-service
zuul:
  routes:
    resource:
      sensitiveHeaders:
      path: /resource/**
      url: http://localhost:8080/
  add-host-header: true
oauth:
  client:
    accessTokenUri: http://localhost:9090/auth/oauth/token
    userAuthorizationUri: http://localhost:9090/auth/oauth/authorize
    clientId: clientIdMock
    clientSecret: clientSecretMock
  resource:
    userInfoUri: http://localhost:7070/resource/rest/me
logging:
  level:
    org.springframework.web.client: TRACE